### PR TITLE
Nvme fix

### LINKED ISSUE #48: Failure using bigboot with nvme block devices
Uncovered a couple related issues while testing `bigboot` role on a RHEL7 instance with nvme block devices. The main issue is that the device special file for the boot partition is not being detected correctly. Here's is an example of the script invocation and resulting error output... 

```
switch_root:/# /usr/bin/bigboot.sh -d="/dev/nvme0n1" -s="800M" -b="1" -p="p"
Device (/dev/nvme0n1) not found
...
```

Following this error message, the `bigboot.sh` script also then output a lengthy usage message which leads to the next issue. The output is too much for `/dev/kmsg`, so rather than seeing the error on the console, we observed this... 

```
[    7.740073] dracut-pre-mount[377]: //lib/dracut/hooks/pre-mount/99-increase-boot-partition.sh: line 27: echo: write error: Invalid argument
```

This resulted in some fun head scratching, but we were finally able to figure out the root cause by adding `rd.break=pre-mount` kernel param and then manually running the script at the emergency shell prompt. 

So there are a few things I want to fix here: 

- Figure out why `bigboot.sh` is getting "device not found" error. 
- Don't output the lengthy usage message when there is any error and correct some inaccuracies.
- Maybe find a sysfs way to identify the actual device names rather than messing prefix strings and partition numbers.

### PR DESCRIPTION
**Pull request by swapdisk**
This fixes #48.

- Remove bad parenthesis in `bigboot.sh` that were the root cause of the "device not found" error.
- Shorten `bigboot.sh` usage help message to not exceed the kmsg buffer.
- Add "partition move is progressing" messages so inpatient operators don't think their server is hung while the `sfdisk --move-data` is running.
- Fix "vgs not found" error I uncovered while testing.

### CODE REVIEW

File: roles/bigboot/files/bigboot.sh [hunk 1]
```diff
@@ -15,37 +15,7 @@ INCREMENT_BOOT_PARTITION_SIZE_IN_BYTES=
...
-    echo "   $>$(basename "$0") /dev/vdb 1073741824"
-    echo ""
-    echo " Will increase the boot partition in /dev/vdb by 1G and shift the adjacent partition in the device by the equal amount."
-    echo ""
-    echo "   Number  Start   End     Size    Type      File system  Flags"
-    echo "           32.3kB  1049kB  1016kB            Free Space"
-    echo "   1       1049kB  12.2GB  12.2GB  primary   ext4         boot"
-    echo "   2       12.2GB  32.2GB  20.0GB  extended"
-    echo "   5       12.2GB  32.2GB  20.0GB  logical   ext4"
+    echo "Usage: $(basename "$0") -d=<device_name> -s=<increase_size_with_units> -b=<boot_partition_number> -p=<partition_prefix>"
```
Comment (ygalblum) [inline roles/bigboot/files/bigboot.sh:18]: I think it can be beneficial to keep the information in the old usage. Maybe in a comment at the start of the file. WDYT?

**Review by ygalblum — COMMENTED** [review]
Great find. I don't remember why I added the parenthesis to begin with.
Other than the comment about the usage LGTM

File: roles/bigboot/files/bigboot.sh (hunk 1 above)
Comment (swapdisk) [reply roles/bigboot/files/bigboot.sh:51]: Done. I dropped the info about "determining which partition number is the boot partition by looking for the boot flag" as that's no longer how it works.

**Review by ygalblum — APPROVED** [review]
LGTM
